//
//  ORKHL7CDA.h
//  ResearchKit
//
//  Created by Andrew Hill on 21/08/2016.
//  Copyright © 2016 researchkit.org. All rights reserved.
//

#import <Foundation/Foundation.h>

@class ORKStep;
@class ORKResult;
@class ORKTaskResult;

/**
 The `ORKHL7CDDSectionType` value indicates which section HL7CDDFragments should be attributed to
 the task.
 */
typedef NS_ENUM(NSInteger, ORKHL7CDASectionType) {
    
    /// The Purpose section represents the specific reason for which the summarization was generated, such as in response to a request...[used only] when the CCD has a specific purpose such as a transfer, referral, or patient request. [CCD 2.8]
    ORKHL7CCDSectionTypePurpose,
    
    /// The Problems section lists and describes all relevant clinical problems at the time the summary is generated. At a minimum, all pertinent current and historical problems should be listed. [CCD 3.5]
    ORKHL7CCDSectionTypeProblems,
    
    /// The Procedures section defines all interventional, surgical, diagnostic, or therapeutic procedures or treatments pertinent to the patient historically at the time the document is generated. The section may contain all procedures for the period of time being summarized, but should include notable procedures.” [CCD 3.14]
    ORKHL7CCDSectionTypeProcedures,
    
    /// The Family History section contains data defining the patient’s genetic relatives in terms of possible or relevant health risk factors that have a potential impact on the patient’s healthcare risk profile. [CCD 3.6]
    ORKHL7CCDSectionTypeFamilyHistory,
    
    /// “The Social History section contains data defining the patient’s occupational, personal (e.g. lifestyle), social, and environmental history and health risk factors, as well as administrative data such as marital status, race, ethnicity and religious affiliation. [CCD 3.7]
    ORKHL7CCDSectionTypeSocialHistory,
    
    /// “The Payers section describes payers and the coverage they provide for defined activities. For each payer, “all the pertinent data needed to contact, bill to, and collect from that payer should be included. Authorization information that can be used to define pertinent referral, authorization tracking number, procedure, therapy, intervention, device, or similar authorizations for the patient or provider or both should be included. [CCD 3.1]
    ORKHL7CCDSectionTypePayers,
    
    /// The Advance Directives section contains data defining the patient’s advance directives and any reference to supporting documentation...  This section contains data such as the existence of living wills, healthcare proxies, and CPR and resuscitation status. [CCD 3.2]
    ORKHL7CCDSectionTypeAdvanceDirectives,
    
    /// The Alerts section is used to list and describe any allergies, adverse reactions, and alerts that are pertinent to the patient’s current or past medical history. [CCD 3.8]
    ORKHL7CCDSectionTypeAlerts,
    
    /// The Medications section defines a patient’s current medications and pertinent medication history. [CCD 3.9]
    ORKHL7CCDSectionTypeMedications,
    
    /// The Immunizations section defines a patient’s current immunization status and pertinent immunization history. [CCD 3.11]
    ORKHL7CCDSectionTypeImmunizations,
    
    /// The Medical Equipment section describes all pertinent equipment relevant to the diagnosis, care, and treatment of a patient.” [CCD 3.10]
    ORKHL7CCDSectionTypeMedicalEquipment,
    
    /// The Vital Signs section may contain all vital signs for the period of time being summarized, but at a minimum should include notable vital signs such as the most recent, maximum and/or minimum, or both, baseline, or relevant trends. [CCD 3.12]
    ORKHL7CCDSectionTypeVitalSigns,
    
    /// The Functional Status section contains information on the “normal functioning” of the patient at the time the record is created. Deviation from normal function and limitations and improvements should be included here. [CCD 3.4]
    ORKHL7CCDSectionTypeFunctionalStatus,
    
    /// The Results section contains the results of observations generated by laboratories, imaging procedures, and other procedures. The section may contain all results for the period of time being summarized, but should include notable results such as abnormal values or relevant trends. [CCD 3.13].
    ORKHL7CCDSectionTypeResults,
    
    /// The Encounters section is used to list and describe any healthcare encounters pertinent to the patient’s current health status or historical health history. [CCD 3.15]
    ORKHL7CCDSectionTypeEncounters,
    
    /// The Plan Of Care section contains all active, incomplete, or pending orders, appointments, referrals,  procedures, services, or any other pending event of clinical significance to the current and ongoing care of the patient ... The plan of care section also contains information regarding goals and clinical reminders. [CCD 3.16]
    ORKHL7CCDSectionTypePlanOfCare
    
};

@interface ORKHL7CDAPerson : NSObject

@property (nonatomic, nullable, copy) NSString *prefix;

@property (nonatomic, nonnull, copy) NSString *givenName;

@property (nonatomic, nonnull, copy) NSString *familyName;

@property (nonatomic, nullable, copy) NSString *suffix;

// Need to check how HL7 does GenderCodes before we finalise this type
@property (nonatomic, nonnull, copy) NSString *gender;

@property (nonatomic, nonnull, copy) NSDate *birthdate;

@end


@interface ORKHL7CDASectionContent : NSObject

@property (nonatomic) ORKHL7CDASectionType sectionType;

@property (nonatomic, nonnull, copy) NSString *templateIDroot;

@property (nonatomic, nonnull, copy) NSString *sectionCode;

@property (nonatomic, nonnull, copy) NSString *title;

@property (nonatomic, nonnull, copy) NSString *framework;

@end

@interface ORKHL7CDATextFragment : NSObject

@property (nonatomic) ORKHL7CDASectionType sectionType;

@property (nonatomic, copy, nonnull) NSString *xmlFragment;

@end

@protocol ORKStepHL7CDATextDelegate <NSObject>

-(nullable ORKHL7CDATextFragment *)hl7CDAtextForStep:(nonnull ORKStep *)step withResult:(nonnull ORKResult *)result;

@end

@interface ORKHL7CDA : NSObject

+(nonnull NSString *)makeHL7CDA:(nonnull ORKTaskResult *)taskResult
                     forPatient:(nonnull ORKHL7CDAPerson *)patient
                  effectiveFrom:(nonnull NSDate *)effectiveFrom
                    effectiveTo:(nonnull NSDate *)effectiveTo
                 assignedPerson:(nonnull ORKHL7CDAPerson *)assignedPerson;

@end
