#
# This source file is part of the Stanford Biodesign Digital Health Group open-source organization
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build XCArchive

on:
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      version:
        description: 'The version number of the framework embedded in the XCArchives.'
        type: string
        required: true

jobs:
  build-xcarchive:
    uses: StanfordBDHG/.github/.github/workflows/archive.yml@v2
    strategy:
      matrix:
        include:
          - configuration: Release
            cxxInterop: false
          - configuration: Debug  # It's only possible to build ResearchKit with enabled C++ interop in Debug configuration
            cxxInterop: true
    with:
      workspaceFile: RKWorkspace.xcworkspace
      xcArchiveName: ResearchKit-${{ matrix.configuration }}
      scheme: ResearchKit
      version: ${{ inputs.version }}
      configuration: ${{ matrix.configuration }}
      cxxInterop: ${{ matrix.cxxInterop }}
      sdk: '["iphoneos", "iphonesimulator", "xros", "xrsimulator"]'
      runsonlabels: '["macOS", "self-hosted"]'
  ios:
    name: Build and Test iOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      path: 'Tests/UITests'
      scheme: TestApp
      resultBundle: TestApp-iOS.xcresult
      artifactname: TestApp-iOS.xcresult
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [ios]
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: TestApp-iOS.xcresult
