#
# This source file is part of the Stanford Biodesign Digital Health Group open-source organization
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build XCArchive

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      version:
        description: 'The version number of the framework embedded in the XCArchives.'
        type: string
        required: true

jobs:
  create-xcframework-and-release-workflow-researchkit:
    name: XCFramework
    uses: StanfordBDHG/.github/.github/workflows/xcframework.yml@v2
    strategy:
      matrix:
        framework: [ResearchKit, ResearchKitUI]
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      workspaceFile: RKWorkspace.xcworkspace
      xcFrameworkName: ${{ matrix.framework }}
      scheme: ${{ matrix.framework }}
      dryRun: true
      version: ${{ inputs.version }}
      configuration: Release
      sdk: '["iphoneos", "iphonesimulator", "xros", "xrsimulator"]'
  create-xcframework-and-release-workflow-researchkit-active-tasks:
    name: XCFramework (ResearchKitActiveTask)
    uses: StanfordBDHG/.github/.github/workflows/xcframework.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      workspaceFile: RKWorkspace.xcworkspace
      xcFrameworkName: ResearchKitActiveTask
      scheme: ResearchKitActiveTask
      dryRun: true
      version: ${{ inputs.version }}
      configuration: Release
      sdk: '["iphoneos", "iphonesimulator"]'
  ios:
    name: Build and Test iOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      path: 'Tests/UITests'
      scheme: TestApp
      resultBundle: TestApp-iOS.xcresult
      artifactname: TestApp-iOS.xcresult
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [ios]
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: TestApp-iOS.xcresult
