name: CI

on:
  push:
    branches: [ 'main', 'dev/3.0' ]
  pull_request:
    branches: [ 'main', 'dev/3.0' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:        
  test:
    runs-on: macos-13
    strategy:
      matrix:
        destination: ['platform=iOS\ Simulator,OS=17.2,name=iPhone\ 15\ Pro\ Max']
        scheme: ['ResearchKit']
    steps:
      - uses: actions/checkout@v4
      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app
      - name: Use multiple cores
        run: defaults write com.apple.dt.XCBuild EnableSwiftBuildSystemIntegration 1
      - name: Test
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -verbose -workspace RKWorkspace.xcworkspace -scheme ${{ matrix.scheme }} -destination ${{ matrix.destination }} build test | xcpretty
